version: '3.9'

services:
  drive-database:
    image: postgres:15
    container_name: vpn-database
    restart: always
    volumes:
      - ./api/infrastructure/database-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: vpn
    networks:
      - external-network
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    container_name: vpn-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-example}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-example}
    networks:
      - external-network
    ports:
      - 6379:6379

networks:
  external-network:
    name: internxt
    external: true
